theme: jekyll-theme-slate
title: Ezra Bible App
description: A modern and user-friendly Bible study app for your desktop and tablet
show_downloads: true
google_analytics: UA-170877550-2
playstore_url: https://play.google.com/store/apps/details?id=net.ezrabibleapp.cordova
github:
  repository_url: https://github.com/ezra-bible-app/ezra-bible-app
  owner_url: https://github.com/tobias-klein
  win_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/1.4.0/ezra-bible-app_win32_setup-1.4.1.exe
  mac_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/1.4.0/ezra-bible-app_mac_1.4.0_x64.dmg
  ubuntu_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/1.4.0/ezra-bible-app_ubuntu2004-1.4.0.deb
  fedora_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/1.4.0/ezra-bible-app_fedora33-1.4.0.rpm
  owner_name: Tobias Klein
