theme: jekyll-theme-slate
title: Ezra Bible App
description: A user-friendly Bible study tool for your desktop and tablet
show_downloads: true
google_analytics: UA-170877550-2
github:
  repository_url: https://github.com/ezra-bible-app/ezra-bible-app
  owner_url: https://github.com/tobias-klein
  win_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/0.17.0/ezra-bible-app_win32_setup-0.17.0.exe
  mac_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/0.17.0/ezra-bible-app_mac_0.17.1_x64.dmg
  ubuntu_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/0.17.0/ezra-bible-app_ubuntu2004-0.17.0.deb
  fedora_url: https://github.com/ezra-bible-app/ezra-bible-app/releases/download/0.17.0/ezra-bible-app_fedora33-0.17.0.rpm
  owner_name: Tobias Klein
